version: '3.8'

services:
  streamer:
    build: .
    environment:
      - LIVEPEER_API_KEY=${LIVEPEER_API_KEY}
      - LIVEPEER_API_HOST=${LIVEPEER_API_HOST}
      - HLS_ANALYZER_API_KEY=${HLS_ANALYZER_API_KEY}
      - HLS_ANALYZER_API_HOST=${HLS_ANALYZER_API_HOST}
      - DISCORD_WEBHOOK=${DISCORD_WEBHOOK}
      - PLAYBACK_REGION=mdw
      - INGEST_REGION=mdw
    volumes:
      - .:/app

  ffmpeg:
    build: .
    entrypoint:
      - ffmpeg
    command:
      - -re
      - -fflags
      - +genpts
      - -stream_loop
      - "-1"
      - -i
      - /opt/bbb_30s.ts
      - -c
      - copy
      - -strict
      - "-2"
      - -bsf:a
      - aac_adtstoasc
      - -f
      - flv
      - rtmp://mdw-rtmp.livepeer.monster/live/74e2-qimo-7aaf-r7kn

  monitor:
    build: .
    volumes:
      - .:/app
    # environment:
      # - STREAM_MONITOR_LABEL_REGION=${REGION}
      # - STREAM_MONITOR_LABEL_DURATION=${DURATION}
    entrypoint:
      - ./bin/stream-monitor
    command:
      - -wait-for-target
      - 120s
      - -rtmp-url
      - ${INJEST_URL}
      - -media-url
      - ${PLAYBACK_URL}
      - -time
      - ${DURATION}
      - -ignore-time-drift
      - -ignore-gaps
      - -v
      - "1"
    ports:
      - 9091:9090

  grafana:
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=12341234
      - GF_USERS_ALLOW_SIGN_UP=false
    image: grafana/grafana:7.1.5
    volumes:
      - ./data/grafana:/var/lib/grafana
    ports:
      - 3000:3000

  prom:
    image: prom/prometheus:v2.20.1
    volumes:
      - ./data/prometheus/config:/etc/prometheus/
      - ./data/prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090
