name: publish-docker-image

on:
  push:
    tags:
      - "*"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

    - name: Build docker image
      run: docker build . --file Dockerfile --tag livepeer/stream-monitor:${{ steps.get_version.outputs.VERSION }}

    - name: Push docker image
      env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u $DOCKER_USERNAME --password-stdin
        docker push livepeer/stream-monitor:${{ steps.get_version.outputs.VERSION }}
